### ISSUE TITLE
Is anybody reading support@golangbridge.org?

### ISSUE THREAD

**Issue by zerkms** [gobridge/CodeOfConduct#5]

**Comment by jboursiquot** [comment]
Hey @zerkms. We've recently switched our Google Apps accounts and it's possible some things may have fallen through the cracks.

How can we help?

**Comment by zerkms** [comment]
I've sent a complaint there, and might forward it wherever is the new correct address.

**Comment by jboursiquot** [comment]
Please resend to the same support@golangbridge.org email address and that should reach us.
